version: 2

before:
  hooks:
    - go mod tidy

builds:
  # Linux Build - eBPF
  - id: "linux"
    main: ./cmd/dnsflux
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=linux
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: dnsflux

  # Windows Build
  - id: "windows"
    main: ./cmd/dnsflux
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}}
    binary: dnsflux

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - "^*.md"
      - "^*.ya?ml"
